### ISSUE TITLE
Replace test by flutter_test

### ISSUE THREAD

**Issue by amorenew** [BirjuVachhani/spider#32]
When I build I got auto-generated test class with
`import 'package:test/test.dart';
`
Could you use flutter_test as it includes the required function of test library?
`import 'package:flutter_test/flutter_test.dart';
`
Thanks a lot

**Comment by BirjuVachhani** [comment]
@amorenew Spider is supposed to work with any dart app. That's why There's no dependency of Flutter. If I make this changes that you're requesting, it will bind tests with Flutter which I don't want.

Besides, `flutter_test` is built on top of `test` package so it is easier to add `test` package to your dev dependencies. And as it is a dev_dependency, it won't affect your app.

**Comment by BirjuVachhani** [comment]
@NicolasDurant I can probably add a configuration flag which you can enable to indicate that it should use `flutter_test` imports in tests.

**Comment by BirjuVachhani** [comment]
This has been fixed and now available in [`v3.1.0`](https://pub.dev/packages/spider/versions/3.1.0)
